/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoclicker;

/**
 *
 * @author vileelf
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    AutoClickerUi au;
    public Options(AutoClickerUi au) {
        initComponents();
        this.au=au;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgClickMethod = new javax.swing.ButtonGroup();
        radToggle = new javax.swing.JRadioButton();
        radHold = new javax.swing.JRadioButton();
        bttSave = new javax.swing.JButton();
        bttCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btgClickMethod.add(radToggle);
        radToggle.setText("Toggle");
        radToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radToggleActionPerformed(evt);
            }
        });

        btgClickMethod.add(radHold);
        radHold.setText("Hold");
        radHold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHoldActionPerformed(evt);
            }
        });

        bttSave.setText("Save");

        bttCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radToggle)
                    .addComponent(radHold))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(bttSave)
                .addGap(18, 18, 18)
                .addComponent(bttCancel)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radHold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSave)
                    .addComponent(bttCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radHoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radHoldActionPerformed

    private void radToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radToggleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radToggleActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgClickMethod;
    private javax.swing.JButton bttCancel;
    private javax.swing.JButton bttSave;
    private javax.swing.JRadioButton radHold;
    private javax.swing.JRadioButton radToggle;
    // End of variables declaration//GEN-END:variables
}
