/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoclicker;

/**
 *
 * @author vileelf
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    AutoClickerUi au;
    boolean getKey;
    boolean getToggleKey;
    public Options(AutoClickerUi au) {
        initComponents();
        this.au=au;
        getKey=false;
        getToggleKey=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgClickMethod = new javax.swing.ButtonGroup();
        radToggle = new javax.swing.JRadioButton();
        radHold = new javax.swing.JRadioButton();
        bttSave = new javax.swing.JButton();
        bttCancel = new javax.swing.JButton();
        txtHotkey = new javax.swing.JTextField();
        txtToggleKey = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btgClickMethod.add(radToggle);
        radToggle.setText("Toggle");
        radToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radToggleActionPerformed(evt);
            }
        });

        btgClickMethod.add(radHold);
        radHold.setSelected(true);
        radHold.setText("Hold");
        radHold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHoldActionPerformed(evt);
            }
        });

        bttSave.setText("Save");

        bttCancel.setText("Cancel");

        txtHotkey.setText("Hotkey");
        txtHotkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtHotkeyMouseReleased(evt);
            }
        });
        txtHotkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotkeyActionPerformed(evt);
            }
        });

        txtToggleKey.setText("Toggle Off Hotkey");
        txtToggleKey.setEnabled(false);
        txtToggleKey.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtToggleKeyFocusGained(evt);
            }
        });
        txtToggleKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtToggleKeyMouseReleased(evt);
            }
        });
        txtToggleKey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtToggleKeyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(bttSave)
                .addGap(18, 18, 18)
                .addComponent(bttCancel)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radToggle)
                    .addComponent(radHold)
                    .addComponent(txtToggleKey)
                    .addComponent(txtHotkey))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radHold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(txtHotkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtToggleKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttSave)
                    .addComponent(bttCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radHoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHoldActionPerformed
        //Hold option Selected
        
    }//GEN-LAST:event_radHoldActionPerformed

    private void radToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radToggleActionPerformed
        //Toggle option Selected
    }//GEN-LAST:event_radToggleActionPerformed

    private void txtHotkeyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHotkeyMouseReleased
        
    }//GEN-LAST:event_txtHotkeyMouseReleased
// mouse hotkey selected
        /*if(getKey){
            au.hotkey=evt.getButton();
            switch(au.hotkey){
                case MouseEvent.BUTTON1:
                    au.mousemask=MouseEvent.BUTTON1_MASK;
                    txtHotkey.setText("Mouse 1");
                    break;
                case MouseEvent.BUTTON2:
                    au.mousemask=MouseEvent.BUTTON2_MASK;
                    txtHotkey.setText("Mouse 2");
                    break;
                case MouseEvent.BUTTON3:
                    au.mousemask=MouseEvent.BUTTON3_MASK;
                    txtHotkey.setText("Mouse 3");
                    break;
                default:
                    au.mousemask=1;
                    break;
            }
            au.mouse=true;
            getKey=false;
        }*/
    private void txtToggleKeyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtToggleKeyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToggleKeyFocusGained

    private void txtToggleKeyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtToggleKeyMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToggleKeyMouseReleased

    private void txtToggleKeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToggleKeyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToggleKeyKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        au.on=true;
        au.setVisible(true);
        System.out.println(au.hotkey);
    }//GEN-LAST:event_formWindowClosing

    private void txtHotkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotkeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotkeyActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgClickMethod;
    private javax.swing.JButton bttCancel;
    private javax.swing.JButton bttSave;
    private javax.swing.JRadioButton radHold;
    private javax.swing.JRadioButton radToggle;
    private javax.swing.JTextField txtHotkey;
    private javax.swing.JTextField txtToggleKey;
    // End of variables declaration//GEN-END:variables
}
